name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.15
        uses: actions/setup-node@v1
        with:
          node-version: "16.15"
      - name: Install yarn and run unittest
        run: |
          yarn
          yarn test
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: my_github_username/my_repository_name/my_image_name
          registry: docker.pkg.github.com
          username: ${{ USERNAME.GITHUB_USERNAME }}
          password: ${{ USERNAME.GITHUB_TOKEN }}
          dockerfile: Dockerfile-prod
          tags: latest
